apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/driosalido/cluster-apps.git
    targetRevision: HEAD
    path: charts/root-charts/cluster-apps
    helm:
      values: |
        region: "eu-west-1"
        clusterName: "infratest-dev"
      valueFiles:
        - clients/infratest/eu-west-1/dev/cluster-apps-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
