apiVersion: v2
name: mysql
description: A Helm chart for mysql
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: mysql
  version: 9.2.6
  repository: https://charts.bitnami.com/bitnami
