apiVersion: v2
name: mysql
description: A Helm chart for mysql
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: bitnami/mysql
  version: 4.4.3
  repository: https://charts.bitnami.com/bitnami
