# Global Values
region: "eu-west-1"
account: "848782056238"
clusterName: "infratest-dev"
namespace: "test-app"
envTag: "dev"
argocdProject: ""

# Wordpress
wordpress:
  enable: false

# mysql Values
mysql:
  enable: false
