# Global Values
repoUrl: "https://github.com/driosalido/cluster-apps.git"
targetRevision: HEAD
region: ""
account: ""
clusterName: ""

# AWS CloudWatch Metrics Values
awsCloudWatchMetrics:
  enable: false
  serviceAccountName:

# Kubernetes Dashboard Values
kubernetesDashboard:
  enable: true
  serviceAccountName:  eks-admin

# mysql Values
mysql:
  enable: true

# sparkOperator
sparkOperator:
  enable: true
